// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process_rule.proto

package iochti.processRule.grpc;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.IdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
